# Prod config overrides base one

version: "3"
services:

  img2sto:
    networks:
      - img2sto

  minio:
    image: minio/minio:RELEASE.2020-12-12T08-39-07Z
    networks:
      - img2sto

  imaginary:
    image: h2non/imaginary:1.2.4
    networks:
      - img2sto

networks:
  img2sto:
