# Dev config overrides base one

version: "3"
services:

  minio:
    image: minio/minio:RELEASE.2020-12-12T08-39-07Z
    ports:
      - "8111:9000"
    environment:
      # Mock keys for dev env
      - MINIO_ACCESS_KEY=5F9HBcm8TZpJmb8r
      - MINIO_SECRET_KEY=XF8wEgaMmsH2B5ne

  imaginary:
    image: h2non/imaginary:1.2.4
    ports:
      - "8112:9000"
